name = "calculator-mcp-server"
main = "worker.js"
compatibility_date = "2023-10-02"

[build]
command = "pip install -r requirements.txt"

[vars]
PYTHON_MODULE = "calculator_mcp_cloudflare"
PYTHON_ENTRYPOINT = "mcp"

[[services]]
binding = "CALCULATOR_SERVICE"
service = "calculator-mcp-server"
environment = "production"